title: Apex App

hosts:
  - name: web
    ip_addresses:
      - 172.168.1.110

  - name: app_1
    ip_addresses:
      - 172.168.1.111

  - name: app_2
    ip_addresses:
      - 172.168.1.112

  - name: app_3
    ip_addresses:
      - 172.168.1.113

  - name: app_db_conn_pool
    ip_addresses:
      - 172.168.1.114

  - name: app_db_1
    ip_addresses:
      - 172.168.1.115

  - name: app_db_2
    ip_addresses:
      - 172.168.1.116

  - name: app_db_3
    ip_addresses:
      - 172.168.1.117

connections:
  - source: web
    target: app_1
    port: '?'
    transport_protocol: '?'
    application_protocol: http
  - source: web
    target: app_2
    port: '?'
    transport_protocol: '?'
    application_protocol: http
  - source: web
    target: app_3
    port: '?'
    transport_protocol: '?'
    application_protocol: http
  - source: app_1
    target: app_db_1
    port: '?'
    transport_protocol: '?'
    application_protocol: sql
  - source: app_2
    target: app_db_2
    port: '?'
    transport_protocol: '?'
    application_protocol: sql
  - source: app_3
    target: app_db_3
    port: '?'
    transport_protocol: '?'
    application_protocol: sql
  - source: app_db_conn_pool
    target: app_db_1
    port: '?'
    transport_protocol: '?'
    application_protocol: sql
  - source: app_db_conn_pool
    target: app_db_2
    port: '?'
    transport_protocol: '?'
    application_protocol: sql
  - source: app_db_conn_pool
    target: app_db_3
    port: '?'
    transport_protocol: '?'
    application_protocol: sql
