nodes:
  - name: web
    ip_addresses:
      - 172.168.1.110
    data_streams:
      - other: app_1
        direction: '->'
        protocol: 'http'
      - other: app_2
        direction: '->'
        protocol: 'http'
      - other: app_3
        direction: '->'
        protocol: 'http'

  - name: app_1
    ip_addresses:
      - 172.168.1.111
    data_streams:
      - other: app_db_1
        direction: '->'
        protocol: 'sql'

  - name: app_2
    ip_addresses:
      - 172.168.1.112
    data_streams:
      - other: app_db_2
        direction: '->'
        protocol: 'sql'

  - name: app_3
    ip_addresses:
      - 172.168.1.113
    data_streams:
      - other: app_db_3
        direction: '->'
        protocol: 'sql'

  - name: app_db_conn_pool
    ip_addresses:
      - 172.168.1.114
    data_streams:
      - other: app_db_1
        direction: '->'
        protocol: 'sql'
      - other: app_db_2
        direction: '->'
        protocol: 'sql'
      - other: app_db_3
        direction: '->'
        protocol: 'sql'

  - name: app_db_1
    ip_addresses:
      - 172.168.1.115

  - name: app_db_2
    ip_addresses:
      - 172.168.1.116

  - name: app_db_3
    ip_addresses:
      - 172.168.1.117

